### ISSUE TITLE
Can't check message.

### ISSUE THREAD

**Issue by Hamachi-geek** [takusan23/NewRadioSupporter#1]
I can't check message when I set my device dark mode.

## Screenshot
<img src="https://lh3.googleusercontent.com/YrWs6RNSCguqjnzlK6yJFCiGyi8vGGKGUSDZI1HNA2SFVyzEgA3pVjGQinSdVXAETmTXjDHiP8nPRoC7DRCp9plllU9kFDQEw6_svxQ45-zEQ0i7RCc6tzutzhSISmRv5hprUARP6ZA=w2400" width="300" />

**Comment by takusan23** [comment]
I fixed it. thanks!

<img width="300px" src="https://user-images.githubusercontent.com/32033405/200625566-be6ecfa5-7a8a-42a9-9bcd-f2da37005448.png">
