### ISSUE TITLE
デュアルSIM環境でSIM1の情報のみ表示される

### ISSUE THREAD

**Issue by Magatama1000** [takusan23/NewRadioSupporter#3]
デュアルSIM環境(物理+eSIM)でこのアプリを利用しています。
どちらでモバイルネットワークを使っていても、このアプリを開くとSIM1の情報のみ表示されます。
SIM2の情報を閲覧可能にして頂けないでしょうか。
以下にこちらの環境を記します。

Google Pixel 7 Pro
Android 13 TD1A.221105.001
SIM1(物理) NTT DOCOMO (MVNO イオンモバイル)
SIM2(eSIM) povo (povo2.0)

**Comment by takusan23** [comment]
遅くなりすいません。
デュアルSIMに対応しました！。最新版にアップデートをお願いします～🙏  
手元の Xperia では動いてるので多分動くと思います、、、
